# Generated by Django 4.1.5 on 2023-12-11 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='class_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=250)),
                ('list_of_student', models.CharField(max_length=20)),
                ('section', models.CharField(max_length=20)),
            ],
        ),
    ]
