# Generated by Django 4.1.5 on 2023-12-11 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0002_students_rename_class_details_clsdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='student_age',
            field=models.IntegerField(default=0),
        ),
    ]
